//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admin_ID { get; set; }
        public string admin_Username { get; set; }
        public string admin_Password { get; set; }
        public string admin_Image { get; set; }
    }
}
