//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string User_Type { get; set; }
        public string User_Username { get; set; }
        public string User_Password { get; set; }
        public string User_Gender { get; set; }
        public string User_Image { get; set; }
        public int User_Contact { get; set; }
        public string Usre_FirstName { get; set; }
        public string User_LastName { get; set; }
        public string User_DOB { get; set; }
    }
}
